version: "3.9"
   
services:

  mongo:
    image: mongo
    volumes:
      - /extHd/fileSystem/mongoData/data:/data/db # Change host directory
    ports:
      - 27017:27017
    restart: always
    
  webportal:
    image: ghcr.io/donsagiv/webportal:latest
    ports:
      - "8080:80" # Change exposed port
    depends_on:
      - mongo
    restart: always
    environment:
      - MONGO_CONN_STR=mongodb://mongo:27017