name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Stop building if it takes longer than 15 minutes.
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    # Used to verify the workflow has started.
    - name: Verify Workflow
      run: echo Running Docker Build and Push

    # Get .NET Core builder
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Build Docker Image
    - name: Build Docker Image
      run: docker build --file ./asagiv.dbmanager.webportal/Dockerfile --build-arg PAT_ARG=${{ secrets.PACKAGE_PAT }} --tag ghcr.io/donsagiv/webportal:latest .

    # Log into Docker
    - name: Log Into Docker
      run: docker login ghcr.io -u DonSagiv -p ${{ secrets.PACKAGE_PAT }}

    #Push Docker Image
    - name: Push Docker Image
      run: docker push ghcr.io/donsagiv/webportal:latest
