name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Stop building if it takes longer than 15 minutes.
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    # Get .NET Core builder
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Set current date time to environemnt variable.
    - name: Set Date Time Variable
      id: date
      run: echo "::set-output name=date::$(date +%y%m%d_%H%M%S)"

    # Used to verify the workflow has started.
    - name: Verify Workflow
      run: echo Running Docker Build and Push ${{ steps.date.outputs.date }}

    # Build Docker Image
    - name: Build Docker Image
      run: docker build --file ./asagiv.dbmanager.webportal/Dockerfile --build-arg PAT_ARG=${{ secrets.PACKAGE_PAT }} --tag ghcr.io/donsagiv/webportal:${{ steps.date.outputs.date }} --tag ghcr.io/donsagiv/webportal:latest .

    # Log into Docker
    - name: Log Into Docker on Github
      run: docker login ghcr.io -u DonSagiv -p ${{ secrets.PACKAGE_PAT }}
      
    - name: Log Into Docker Hub
      run: docker login -u donsagiv -p ${{ secrets.DOCKER_PWD }}

    # Push Docker Image for Date Tag to Github
    - name: Push Docker Image Github - Date Tag 
      run: docker push ghcr.io/donsagiv/webportal:${{ steps.date.outputs.date }}
      
    # Push Docker Image for Latest Tag to Github
    - name: Push Docker Image Github - Latest Tag
      run: docker push ghcr.io/donsagiv/webportal:latest
      
    # Push Docker Image for Date Tag to Docker Hub Public Repo
    - name: Push Docker Image Docker Hub - Date Tag 
      run: docker push donsagiv/dbmanager:${{ steps.date.outputs.date }}
      
    # Push Docker Image for Latest Tag to Docker Hub Public Repo
    - name: Push Docker Image Docker Hub - Latest Tag
      run: docker push donsagiv/dbmanager:latest
