name: Publish to Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Stop building if it takes longer than 15 minutes.
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    # Used to verify the workflow has started.
    - name: Verify Workflow
      run: echo Running Publish to Nuget

    # Get .NET Core builder
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Push Build Docker Images
    - name: Build Docker Image
      run: docker build . --file ./asagiv.dbmanager.webportal/Dockerfile --build-arg PAT_ARG=${{ sa }}